### ISSUE TITLE
There is no shrug in the README.md ¯\_(ツ)_/¯

### ISSUE THREAD

**Issue by gentakojima** [koopaconan/chrome-shrug#1]
The ¯\_(ツ)_/¯ should be on every step of the installation process, the title, the footer, and everywhere else, if applicable. Or even not.

I find your lack of shrug disturbing ¯\_(ツ)_/¯

**Comment by gentakojima** [comment]
Please, be careful. 

It looks like the anti-shrug evil league has made its way into the markdown consortium and tried to render the innocent shrug unreadable by severing his left arm.

As a workaround, just add a second left arm. That should render the anti-shrug evil league efforts useless.

¯\\_(ツ)_/¯

**Comment by theisolinearchip** [comment]
Added a ¯\\\_(ツ)\_/¯ in the README.md
